### ISSUE TITLE
Submission of pyspark jobs

### ISSUE THREAD

**Issue by jrosskopf** [spotify/spydra#30]
I wan't to submit pyspark jobs using Spydra. Either the documentation is lacking on this end, or the current implementation is not able to handle this job type (I would say, the latter is the case by skimming over the code which generates the `gcloud dataproc jobs submit pyspark` command). 

I get the following error message:
```
ERROR: (gcloud.dataproc.jobs.submit.pyspark) argument PY_FILE is required
Usage: gcloud dataproc jobs submit pyspark PY_FILE --cluster=CLUSTER [optional flags] [-- JOB_ARGS ...]
```
The problem is, that I'm unable with `options` and `job_args` to insert the filename into the command line.

**Comment by jstck** [comment]
Correct, current implementation only supports Hadoop jobs (i.e. `gcloud dataproc jobs submit hadoop ...`)

**Comment by steffengr** [comment]
Hi jrosskopf,

We have never tested it with pyspark and the submission command line seems to differ from the usual one so the code needs to be adjusted to support this case. The problem is that is is neither an option nor an argument to the actual job.

It should be pretty simple to support this case by adding an additional optional argument to SpydraArgument and then extract it in GcloudExecutor.

Would you be interested in fixing this and providing a PR? We are always happy about contributions. We can help you out with the code base if you have any related questions.

**Comment by Xeago** [comment]
@jrosskopf could you give the branch from the pull request a try? I've added a [`py_file`](https://github.com/spotify/spydra/pull/41/commits/fe950792ef1c104c17e69b5f575d67d778a233fd#diff-6cee08773e9a0ced800d29ffd4b26913R85) field to the configuration file.
 
There's instructions to build from source in the README.md, to build the package to use the open source provided init-actions (without hosting your own): `mvn clean package -Dinit-action-uri=gs://spydra-init-actions/spydra -Dtest-configuration-dir=../travis_files`.

Let me know if it works or if you have problems building from source. :)

**Comment by jrosskopf** [comment]
Sure. The pull request was faster than expected. I will give it a try tomorrow and report back.

**Comment by Xeago** [comment]
Ha, I got it to work!

I initially used the first [pyspark wordcount example](http://deelesh.github.io/hello-pyspark-world.html) I found, but that blew up on `__file__` not being readable when running on dataproc. I replaced to an object on GCS and got output!

**Comment by jrosskopf** [comment]
Hey, I also tried it. Works for me. Thank you for effort and quick implementation. 
(It would be so cool, if could use now spydra to also submit to AWS EMR ;))
